config/routes.rb
RisingGuilds::Application.routes.draw do 
   root :to =>"pages#show", :id => "home"
   
   # Static Pages Route
   match 'pages/:id' => 'pages#show'
   
   # Authentication Routes
   match '/logout' => 'user_sessions#destroy', :as => :logout
   match '/login' => 'user_sessions#new', :as => :login
   match '/register' => 'users#create', :as => :register
   match '/signup' => 'users#new', :as => :signup
   match '/rating' => 'rating#index', :as => :rating #:register
   match '/register/:activation_code' => 'activations#new', :as => :register
   match '/activate/:id' => 'activations#create', :as => :activate
   
   #Resources
   resource :account, :controller => "users"
   resources :password_resets
   resource :user_session
   resources :users do
     resources :characters
     resources :guilds
     resources :raids
   end
       
   resources :guilds do
     resources :characters
     resources :users
     resources :raids
     resources :newsentries
     resources :events
     resources :statistics
     resources :widgets
   end
   resources :characters do
     resources :events
   end
   resources :events
   resources :newsentries
   
   resources :raids do
     resources :attendances
   end
   resources :attendances
   
   #Guild Join Route
   match '/guilds/:id/join/:token' => 'guilds#join'
   
   #Default Route
   match ':controller/:id/:action(.:format)'
end

app/models/raid.rb
class Raid < ActiveRecord::Base
  has_and_belongs_to_many :guilds
  has_many :attendances
  has_many :characters, :through => :attendances
  belongs_to :guild
  
  serialize :limit_roles, Hash
  serialize :limit_classes, Hash
  
  attr_accessor :invitation_window, :duration, :invited_guild
  
  validates_presence_of :title

  #only future Date/Time is valid
  validates_each(:invite_start,:start,:end) do |record, attr, value|
    record.errors.add attr, 'have to be in the future' if value < Time.now
  end

  validates_each(:invite_start) do |record, attr, value|
    record.errors.add attr, 'have to happen befor start' if value > record.start
  end
  
  validates_each(:end) do |record, attr, value|
    record.errors.add attr, 'have to happen after start' if value < record.start
  end
  
  def users
    self.characters.map{|c| c.user}
  end

  def invitation_window
    return 15 if new_record?
    if @invitation_window.nil?
      return Integer((self.start.to_f - self.invite_start.to_f) / 60.to_f)
    else
      return @invitation_window
    end
  end
  
  def duration
    return 1 if new_record?
    if @duration.nil?
      return Integer((self.end - self.start).to_f / 3600.to_f)
    else
      return @duration
    end
  end
  
  def date
    self.start.to_date
  end
  
  def levelrange
    if self.min_lvl.nil? && self.max_lvl.nil?
      return "1 - 80"
    elsif self.max_lvl.nil?
      return self.min_lvl.to_s + " - 80"
    elsif self.min_lvl.nil?
      return "1 - " + self.max_lvl.to_s
    else
      return self.min_lvl.to_s + " - " + self.max_lvl.to_s
    end
  end
  
  def closed?
    return false if self.new_record?
    self[:closed] || self.invite_start < Time.now
  end
  
end

app/controllers/raids_controller.rb
class RaidsController < ApplicationController
  filter_resource_access
  
  before_filter :setup_raidicons, :only => [:edit, :new, :create, :update]
  before_filter :setup_guild_id
  
  add_breadcrumb "Home", :root_url
  
  layout :choose_layout
  
  # GET /raids
  # GET /raids.xml
  def index
    @date = params[:month] ? Date.parse(params[:month]) : Date.today

    if !@guild.nil?
      add_breadcrumb @guild.name, guild_path(@guild)
      add_breadcrumb "Raids", :guild_raids_path
      @raids = @guild.raids.where("created_at > ?", Time.now - 1.month).order("start ASC").all
    elsif !params[:user_id].nil?
      add_breadcrumb 'Account', :account_path
      add_breadcrumb "Raids", :user_raids_path
      @raids = current_user.guilds.collect{|g| g.raids.where("created_at > ?", Time.now - 1.month).order("start ASC")}.flatten
    else
      add_breadcrumb "Raids", :raids_path
      if current_user.admin?
        @raids = Raid.all
      else
        @raids = current_user.guilds.collect{|g| g.raids.where("created_at > ?", Time.now - 1.month).order("start ASC")}.flatten
      end
    end

    unless @raids.empty?
      @upcoming_raids = @raids.find_all{|raid| raid.invite_start > DateTime.now} 
      @past_raids = @raids.find_all{|raid| raid.end < DateTime.now}.reverse
      @running_raids = @raids.find_all{|raid| raid.start <= DateTime.now && raid.end >= DateTime.now}
      @newest = @raids.sort{|a,b| b.updated_at <=> a.updated_at}.first.updated_at
    else
      @newest = nil
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @raids }
    end
  end

  # GET /raids/1
  # GET /raids/1.xml
  def show
    if !params[:guild_id].nil?
      add_breadcrumb @guild.name, guild_path(@guild)
      add_breadcrumb "Raids", guild_raids_path(@guild)
      add_breadcrumb @raid.title, :guild_raid_path
    else
      add_breadcrumb "Raids", raids_path
      add_breadcrumb @raid.title, raid_path(@raid)
    end
    
    if @raid.attendances.nil? || current_user.characters.nil? || @raid.attendances.where(:character_id => current_user.characters.collect{|c| c.id}).all.empty?
      @attendance = Attendance.new(:raid_id => @raid.id)
    else
      @attendance = @raid.attendances.where(:character_id => current_user.characters.collect{|c| c.id}).first
    end 
    @guild = @raid.guild
    respond_to do |format|
      format.html # show.html.erb
      format.json do 
        @raid.invitation_window = Integer((@raid.start.to_f - @raid.invite_start.to_f) / 60.to_f)
        @raid.duration = Integer((@raid.end - @raid.start).to_f / 3600.to_f)
        render :json => @raid.to_json(:methods => [:invitation_window, :duration]) 
      end
    end
  end

  # GET /raids/new
  # GET /raids/new.xml
  def new
    add_breadcrumb "Raids", raids_path
    add_breadcrumb "New", new_raid_path
    
    @raid.leader = current_user.id
  	
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @raid }
    end
  end

  # GET /raids/1/edit
  def edit
    if !@guild.nil?
      add_breadcrumb @guild.name, guild_path(@guild)
      add_breadcrumb "Raids", guild_raids_path(@guild)
      add_breadcrumb @raid.title, guild_raid_path(@guild,@raid)
      add_breadcrumb "Edit", edit_guild_raid_path(@guild,@raid)
    else
      add_breadcrumb "Raids", raids_path
      add_breadcrumb @raid.title, raid_path(@raid)
      add_breadcrumb "Edit", edit_raid_path(@raid)
    end
    
    if @raid.closed?
      flash[:error] = t('raids.closed')
      redirect_to guild_raids_path(@raid.guild)
      return true
    end
    
    @raid.limit_roles = {} if @raid.limit_roles.nil?
    @raid.limit_classes = {} if @raid.limit_classes.nil?
    
    @raid.invitation_window = Integer((@raid.start.to_f - @raid.invite_start.to_f) / 60.to_f)
    @raid.duration = Integer((@raid.end - @raid.start).to_f / 3600.to_f)
    
    @possible_leaders = Hash.new
    guild_leaders = @raid.guild.leaders + @raid.guild.officers + @raid.guild.raidleaders
    guild_leaders.each do |user|
      @possible_leaders[user.login] = user.id
    end
  end

  # POST /raids
  # POST /raids.xml
  def create
    @raid.limit_roles = params[:limit_roles].delete_if{|k,v| v.blank?}
    @raid.end = @raid.start + params[:raid][:duration].to_i.hours
    @raid.invite_start = @raid.start - params[:raid][:invitation_window].to_i.minutes
    @raid.guilds << @raid.guild
    @raid.icon = "nil.png" if @raid.icon.blank?
    respond_to do |format|
      if @raid.save
        flash[:notice] = t(:created, :item => 'Raid')
        format.html { redirect_to guild_raid_path(@raid.guild, @raid) }
        format.xml  { render :xml => @raid, :status => :created, :location => @raid }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @raid.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /raids/1
  # PUT /raids/1.xml
  def update
    unless params[:raid][:invited_guild].nil?
      unless @raid.guilds.map{|g| g.name}.include?(params[:raid][:invited_guild])
        @raid.guilds << Guild.where(:name => params[:raid][:invited_guild]) 
        flash[:notice] = t('raids.guild_to_raid')        
      end
      redirect_to guild_raid_path(@raid.guild, @raid)
      return true
    end
      
    @start_time = DateTime.civil(params[:raid][:"start(1i)"].to_i, params[:raid][:"start(2i)"].to_i, params[:raid][:"start(3i)"].to_i, params[:raid][:"start(4i)"].to_i, params[:raid][:"start(5i)"].to_i)
    @end_time = @start_time + params[:raid][:duration].to_i.hours
    @invite_start_time =  @start_time - params[:raid][:invitation_window].to_i.minutes
    
    params[:raid][:"invite_start(1i)"] = @invite_start_time.year.to_s
    params[:raid][:"invite_start(2i)"] = @invite_start_time.month.to_s
    params[:raid][:"invite_start(3i)"] = @invite_start_time.day.to_s
    params[:raid][:"invite_start(4i)"] = @invite_start_time.hour.to_s
    params[:raid][:"invite_start(5i)"] = @invite_start_time.min.to_s
    
    params[:raid][:"end(1i)"] = @end_time.year.to_s
    params[:raid][:"end(2i)"] = @end_time.month.to_s
    params[:raid][:"end(3i)"] = @end_time.day.to_s
    params[:raid][:"end(4i)"] = @end_time.hour.to_s
    params[:raid][:"end(5i)"] = @end_time.min.to_s
    
    @raid.limit_roles = params[:limit_roles].delete_if{|k,v| v.blank?}
    @raid.limit_classes = params[:limit_classes].delete_if{|k,v| v.blank?}
    
    params[:raid][:icon] = "nil.png" if params[:raid][:icon].blank?
    
    respond_to do |format|
      if @raid.update_attributes(params[:raid])
        flash[:notice] = t(:updated, :item => 'Raid')
        format.html { redirect_to guild_raid_path(@raid.guild, @raid) }
        format.xml  { head :ok }
      else
        format.html { redirect_to edit_guild_raid_path(@raid.guild, @raid) }
        format.xml  { render :xml => @raid.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /raids/1
  # DELETE /raids/1.xml
  def destroy
    @guild = @raid.guild
    expire_fragment(@raid)
    @raid.destroy
    respond_to do |format|
      format.html { redirect_to(guild_raids_path(@guild)) }
      format.xml  { head :ok }
    end
  end
  
  def uninvite_guild
    @guild = Guild.find(params[:uninvited_guild])
    respond_to do |format|
      unless @raid.guild == @guild
        if @raid.guilds.delete(@guild)
          flash[:notice] = t('raids.uninvited')
        end
      else
        flash[:error] = t('raids.cant_uninvite')
      end
      format.html { redirect_to guild_raid_path(@raid.guild, @raid) }
    end
  end
  
  protected
  
  def setup_raidicons
    raid_icons_files = Dir.entries(Rails.root.to_s + "/public/images/icons/raid").reject {|f| f[0,1] == "." || f == "nil.png"} 
  	@raid_icons = {}
  	raid_icons_files.each{|f| @raid_icons[f.chomp(".png")] = f}
  	@raid_icons = @raid_icons.sort
  end
  
  def setup_guild_id
    @guild = Guild.find(params[:guild_id]) unless params[:guild_id].nil?
  end
  
  def choose_layout
    unless params[:guild_id].nil?
      return 'guild_tabs'
    else
      return 'application'
    end
  end
  
end

app/helpers/raids_helper.rb
module RaidsHelper

  def approve_style_helper(approved)
    if approved
      return "color:green;"
    else
      return "color:red;"
    end
  end

end

app/views/raids/edit.html.erb
<%= render :partial => 'form', :locals => {:raid => @raid, :raid_icons => @raid_icons} %>

app/views/raids/index.html.erb
<div id="content_menu">
	<ul>
		<% if permitted_to?(:create, :raids) %>
		<% if params[:guild_id] %>
		<li><%= link_to 'New raid', new_guild_raid_path(@guild) %></li>
		<% else %>
		<li><%= link_to 'New raid', new_raid_path %></li>
		<% end %>
		<% end %>
	</ul>
</div>

<% cache (["raid_index", current_user.id, if params[:month] then params[:month] else @date.strftime("%Y/%m") end, @raids]) do %>
<% unless @raids.nil? || @raids.empty? %>
<div id="calendar">
	<h2 id="month">
	  <%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y/%m") %>
	  <%=h @date.strftime("%B %Y") %>
	  <%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y/%m") %>
	</h2>
	<%= calendar_for @raids, :year => @date.year, :month => @date.month do |calendar| %>
	  <%= calendar.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday') %>
	  <%= calendar.day(:day_method => :start) do |date, raids| %>
		<%= date.day %>
		<ul>
		  <%- for raid in raids -%>
		    <li><a href="<%= guild_raid_path(raid.guild, raid) %>" class="raidlink"><%= image_tag("icons/raid/#{raid.icon}", :size => "30x30", :class => "raidicon_small") %><%=h raid.title %></a></li>
		  <%- end -%>
		</ul>
	  <%- end -%>
	<%- end -%>
</div>

<table>
  <thead>
	<tr>
		<th></th>
    	<th>Guild</th>
    	<th>Title</th>
    	<th>Date</th>
    	<th>Invite start</th>
    	<th>Start</th>
    	<th>End</th>
    	<th>Leader</th>
		<th class="narrow">Max</th>
		<th class="narrow">In</th>
    	<th class="narrow">Closed</th>
		<th class="narrow"></th>
		<th class="narrow"></th>
  	</tr>
  </thead>
  <tbody>
	<tr class="header">
		<th></th>
		<th colspan="7"><%= image_tag('icons/door_in.png')%> Upcoming Raids</th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
	</tr>
	<%= render :partial => "raid", :collection => @upcoming_raids %>
  </tbody>
  <tbody>
	<tr class="header">
		<th></th>
		<th colspan="7"><%= image_tag('icons/door_open.png')%> Running Raids</th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
	</tr>	
	<%= render :partial => "raid", :collection => @running_raids %>
  </tbody>
  <tbody>
	<tr class="header">
		<th></th>
		<th colspan="7"><%= image_tag('icons/door.png')%> Past Raids</th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
	</tr>
	<%= render :partial => "raid", :collection => @past_raids %>
  </tbody>
</table>
<% else %>
<p>There are no raids which could be attended by you</p>
<% end %>
<% end %>

app/views/raids/new.html.erb
<%= render :partial => 'form', :locals => {:raid => @raid, :raid_icons => @raid_icons} %>

app/views/raids/show.html.erb
<div id="content_menu">
  <ul>
    <% permitted_to? :edit, @raid do %>
      <li><%= params[:guild_id].nil? ? link_to("Edit",edit_raid_path(@raid)) : link_to("Edit",edit_guild_raid_path(Guild.find(params[:guild_id]),@raid))%></li>
    <% end %>
    <% permitted_to? :destroy, @raid do %>
      <li><%= link_to('Destroy', @raid, :confirm => 'Are you really sure? Destroyed raids can\'t be restored!', :method => :delete) %></li>
    <% end %>
  </ul>
</div>

<% cache(["raid_show", @raid]) do %>
<div style="position:relative; width:100%">	
  <%- @raid.icon = "nil.png" if @raid.icon == "" -%>
  <div id="raidicon"><%= image_tag("/images/icons/raid/#{@raid.icon}", :size => "65x65") %></div>
</div>

<h1><%= @raid.title %></h1>

<% if @raid.start > Time.now %>
  <h4>Raid starts in <%= time_ago_in_words(@raid.start)%></h4>
<% end %>

<% unless @raid.description.empty? %>
  <div id="description">
    <%= @raid.description %>
  </div>
<% end %>

<div class="box_big">
	<div class="box_headline">Details</div>
	<table width="100%" border="0" cellspacing="1" cellpadding="0" class="contentRaid">
	  <tr>
	    <td width="25%"><div align="left" class="raidcontent"><b>participating Guilds</b>:</div></td>
	    <td width="25%"><div align="left" class="raidcontent"><% @raid.guilds.each do |g| %>
	          <ul class="guildslist">
	            <li><%= link_to(g.name, guild_path(g))  %> <%= link_to(image_tag("icons/kick.png", :size => "10x10"), :controller => 'raids', :action => 'uninvite_guild', :id => @raid.id, :uninvited_guild => g.id) if permitted_to?(:uninvite_guild, @raid) && g != @raid.guild %></li>
	          </ul><% end %>
	      </div></td>
	    <td colspan="2" width="50%">
	      <% if permitted_to? :edit %>
	        <%= form_for(@raid) do |f| %>
	          <%= f.text_field :invited_guild %>
	          <%= f.submit 'Invite' %>
	        <% end %>
	      <% end %>
	      </div></td>
	  </tr>

	  <tr>
	    <td><div align="left" class="raidcontent"><b>Raidleader</b>:</div></td>
	    <td><div align="left" class="raidcontent"><span class="leader"><%= User.find(@raid.leader).login %></span></div></td>
	    <td><div align="left" class="raidcontent"><b>Level Range</b>:</div></td>
	    <td><div align="left" class="raidcontent"><%= @raid.levelrange %></div></td>
	  </tr>

	  <tr>
	    <td><div align="left" class="raidcontent"><b>Invite Start</b>:</div></td>
	    <td><div align="left" class="raidcontent"><%= @raid.date %> @ <%= @raid.invite_start.strftime("%H:%M") %></div></td>
	    <td><div align="left" class="raidcontent"><b>Confirmed Members</b>:</div></td>
	    <td><div align="left" class="raidcontent"><% att_s = @raid.attendances.find_all_by_status(3).count %><%= "#{att_s}/#{@raid.max_attendees} (#{Integer(att_s.to_f / @raid.max_attendees.to_f * 100)}%)"%></div></td>
	  </tr>

	  <tr>
	    <td><div align="left" class="raidcontent"><b>Start</b>:</div></td>
	    <td><div align="left" class="raidcontent"><%= @raid.date %> @ <%= @raid.start.strftime("%H:%M") %></div></td>
	    <td><div align="left" class="raidcontent"><b>Available Members </b>:</div></td>
	    <td><div align="left" class="raidcontent"><% att_s = @raid.attendances.find_all_by_status(2).count %><%= "#{att_s}/#{@raid.max_attendees} (#{Integer(att_s.to_f / @raid.max_attendees.to_f * 100)}%)"%></div></td>
	  </tr>

	  <tr>
	    <td><div align="left" class="raidcontent"><b>End</b>:</div></td>
	    <td><div align="left" class="raidcontent"><%= @raid.date %> @ <%= @raid.end.strftime("%H:%M") %></div></td>
	    <td><div align="left" class="raidcontent"><b>Not Available Members </b>:</div></td>
	    <td><div align="left" class="raidcontent"><%= @raid.attendances.find_all_by_status(1).count %></div></td>
	  </tr>
	  <% unless @raid.min_ail.blank? %>
	  <tr>
	    <td></td>
	    <td></td>
	    <td><div align="left" class="raidcontent"><b>Min Ail</b>:</div></td>
	    <td><div align="left" class="raidcontent"><%= @raid.min_ail %></div></td>
	  </tr>
	  <% end %>
	</table>
</div>
<% unless @raid.limit_roles.blank? && @raid.limit_classes.blank? %>
<div class="box_big">
	<div class="box_headline">Limits</div>
  <table>
    <thead>
      <tr>
        <td style="width:200px"></td>
        <% unless @raid.limit_roles.blank? %>
        <% configatron.raidplanner.roles.each do |role| %>
          <td style="width:40px"><%= roleicon(role.downcase) %></td>
        <% end %>
        <% end %>
        <% unless @raid.limit_classes.blank?%>
          <td style="width:40px"></td>
          <% CLASSES.each do |key,value| %>
            <td style="width:40px"><%= image_tag classicon_path(Character.new(:class_id => value)),:size => "18x18" %></td>
          <% end %>
        <% end %>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="left">Confirmed</td>
        <% unless @raid.limit_roles.blank?%>
          <% configatron.raidplanner.roles.each do |role| %>
            <td>
              <% unless @raid.limit_roles[role].blank? %><%= @raid.attendances.where(:role => role, :status => 3).count %>/<%= @raid.limit_roles[role] %> <%= "(#{Integer(@raid.attendances.where(:role => role, :status => 3).count.to_f / @raid.limit_roles[role].to_f * 100)}%)"%><% end %>
            </td>
          <% end %>
        <% end %>
        <% unless @raid.limit_classes.blank?%>
          <td></td>
          <% configatron.raidplanner.classes.each_with_index do |klass,i| %>
            <td>
              <% unless @raid.limit_classes[klass].blank? %><%= @raid.attendances.where(:status => 3).delete_if{|a| a.character.class_id != i+1}.count %>/<%= @raid.limit_classes[klass] %> <%= "(#{Integer(@raid.attendances.where(:status => 3).delete_if{|a| a.character.class_id != i+1}.count.to_f / @raid.limit_classes[klass].to_f * 100)}%)"%><% end %>
            </td>
          <% end %>
        <% end %>
        <td></td>
      </tr>
      <tr>
        <td class="left">Available</td>
        <% unless @raid.limit_roles.blank? %>
          <% configatron.raidplanner.roles.each do |role| %>
            <td>
              <% unless @raid.limit_roles[role].blank? %><%= @raid.attendances.where(:role => role, :status => 2).count %>/<%= @raid.limit_roles[role] %> <%= "(#{Integer(@raid.attendances.where(:role => role, :status => 2).count.to_f / @raid.limit_roles[role].to_f * 100)}%)"%><% end %>
            </td>
          <% end %>
        <% end %>
        <% unless @raid.limit_classes.blank?%>
          <td></td>
          <% configatron.raidplanner.classes.each_with_index do |klass,i| %>
            <td>
              <% unless @raid.limit_classes[klass].blank? %><%= @raid.attendances.where(:status => 2).delete_if{|a| a.character.class_id != i+1}.count %>/<%= @raid.limit_classes[klass] %> <%= "(#{Integer(@raid.attendances.where(:status => 2).delete_if{|a| a.character.class_id != i+1}.count.to_f / @raid.limit_classes[klass].to_f * 100)}%)"%><% end %>
            </td>
          <% end %>
        <% end %>
        <td></td>
      </tr>
    </tbody>
  </table>
</div>
<% end %>
<% end %>
<div class="box_big">
	<div class="box_headline">Attendees</div>
	<div class="box_menu">
		<% if @raid.closed?%>
		  <span class="box_menu_info">The Raid is closed!</span>
		<% else %>
			<% if @attendance.new_record? %>
		  	<% if !current_user.characters.empty? %>
					<span><%= link_to 'Attend Raid', new_raid_attendance_path(@raid), {:class => 'popup',:title => 'New Attendance', :id => 'new_attendance'} %></span>
		  	<% else %>
		    	<span class="box_menu_info">Please connect a character to your account</span>
		  	<% end %>
			<% else %>
				<span><%= link_to 'Edit Attendance', edit_attendance_path(@attendance), {:class => 'popup',:title => 'Edit Attendance'} %></span>
			<% end %>
		<% end %>
	</div>

	<table width="100%" cellpadding="0" cellspacing="0" border="0" >
	  <thead>
	    <tr>
	      <th style="text-align: left;">Name</th>
	      <th class="narrow">Level</th>
	      <th class="narrow">Race</th>
	      <th class="narrow">Class</th>
	      <th class="narrow">Role</th>
	      <th style="text-align: left;">Message</th>
	      <th class="narrow"></th>
				<th class="narrow"></th>
				<th class="narrow"></th>
	    </tr>
	  </thead>
	  <% configatron.raidplanner.status_manager.size.downto(1) do |i| %>
	    <tbody>
	      <tr valign="top" class="header">
	        <th colspan="6"><%=h configatron.raidplanner.status_manager.key(i) %></th>
	        <th></th>
					<th></th>
					<th></th>
	      </tr>
	      <% @raid.attendances.find_all_by_status(i).each do |attendance|%>
	        <tr>
	          <td class="left"><%= link_to attendance.character.name, character_path(attendance.character) %></td>
	          <td><%=h attendance.character.level %></td>
	          <td><%= image_tag raceicon_path(attendance.character),:size => "18x18" %></td>
	          <td><%= image_tag classicon_path(attendance.character),:size => "18x18" %></td>
	          <td><%=h attendance.role %></td>
	          <td  class="left"><%=h attendance.message %></td>
	          <td><%= link_to((attendance.status==3 ? image_tag('icons/arrow_down.png',:title => 'reject') : image_tag('icons/arrow_up.png',:title => 'approve')), {:controller => :attendances, :id => attendance.id , :action => :approve}) if permitted_to?(:approve,attendance) && (i==2 || i==3) && !@raid.closed?%></td>
						<td><%= link_to(image_tag('icons/page_edit.png',:title => 'edit'), edit_attendance_path(attendance), {:class => 'popup',:title => 'Edit Character'}) if permitted_to?(:edit,attendance) %></td>
						<td><%= link_to(image_tag('icons/cross.png',:title => 'destroy'), attendance_path(attendance) ,:confirm => "Are you sure?", :method=>:delete) if permitted_to?(:destroy,attendance) %></td>
	        </tr>
	      <% end %>
	    </tbody>
	  <% end %>
	</table>
</div>

<% permitted_to?(:edit, @raid) do %>
<div class="box_big">
	<div class="box_headline">Add Character</div>
	<%= form_for(:attendance, :url => raid_attendances_path(@raid), :methode => :post) do |f| %>
	<%= f.error_messages %>
	<table>
		<tr>
			<td>
			<script>
				$(function() {
					var characters = [<%= raw( @raid.guilds.map{|g| g.characters}.flatten.map{|c| "\"" + c.name + "\""}.join(',')) %>];
					$( "#character_name" ).autocomplete({
						source: characters
					});
				});
			</script>
			<%= f.label :character %>: <%= text_field_tag(:character_name) %>		
			<td><%= f.label :role %>: <%= f.select(:role, configatron.raidplanner.roles, {:prompt => t('characters.role')}) %></td>			
			<td><%= f.label :status %>: <%= f.select(:status, configatron.raidplanner.status, {:selected => 2}) %></td>			
			<td><%= f.label :message %>: <%= f.text_field :message %></td>
			<td><%= f.submit "Create"%></td>
			<%= f.hidden_field :raid_id %>
		</tr>
	</table>
	<% end %>
</div>
<% end %>

<script>
  $(function() {
    $( "#raid_invited_guild" ).autocomplete({
      source: "/guilds.json",
      minLength: 2,
    });
  });
</script>