config/routes.rb
RisingGuilds::Application.routes.draw do 
   root :to =>"pages#show", :id => "home"
   
   # Static Pages Route
   match 'pages/:id' => 'pages#show'
   
   # Authentication Routes
   match '/logout' => 'user_sessions#destroy', :as => :logout
   match '/login' => 'user_sessions#new', :as => :login
   match '/register' => 'users#create', :as => :register
   match '/signup' => 'users#new', :as => :signup
   match '/rating' => 'rating#index', :as => :rating #:register
   match '/register/:activation_code' => 'activations#new', :as => :register
   match '/activate/:id' => 'activations#create', :as => :activate
   
   #Resources
   resource :account, :controller => "users"
   resources :password_resets
   resource :user_session
   resources :users do
     resources :characters
     resources :guilds
     resources :raids
   end
       
   resources :guilds do
     resources :characters
     resources :users
     resources :raids
     resources :newsentries
     resources :events
     resources :statistics
     resources :widgets
   end
   resources :characters do
     resources :events
   end
   resources :events
   resources :newsentries
   
   resources :raids do
     resources :attendances
   end
   resources :attendances
   
   #Guild Join Route
   match '/guilds/:id/join/:token' => 'guilds#join'
   
   #Default Route
   match ':controller/:id/:action(.:format)'
end

app/controllers/rating_controller.rb
class RatingController < ApplicationController
  def index
    @guilds = Guild.find_all_by_verified(true).paginate :page => params[:page], :per_page => 20, :order => "rating DESC"
  end
end

app/helpers/rating_helper.rb
module RatingHelper
end

app/views/rating/index.html.erb
<h1><%= t('ratings.guild_rating') %></h1>

<table>
  <thead>
	<tr>
		<th>#</th>
		<th><%= t('characters.name') %></th>
		<th><%= t('ratings.rating') %></th>
		<th><%= t('guilds.details.members') %></th>
		<th><%= t('guilds.website') %></th>
	</tr>
	</thead>
	<tbody>
	<% @guilds.each_with_index do |guild,i| %>
	<tr>
		<td><%= "#{i+1}." %></td>
		<td><%= link_to h(guild.name), guild_path(guild) %></td>
		<td><% unless guild.rating.nil? %><%= guild.rating %><% else %><%= t('raitings.not_aviable') %><% end %></td>
		<td><%= guild.characters.count %></td>
		<td><%= link_to guild.website, guild.website %></td>
	</tr>	
	<% end %>
  </tbody>
</table>
<%= will_paginate @guilds%>