config/routes.rb
RisingGuilds::Application.routes.draw do 
   root :to =>"pages#show", :id => "home"
   
   # Static Pages Route
   match 'pages/:id' => 'pages#show'
   
   # Authentication Routes
   match '/logout' => 'user_sessions#destroy', :as => :logout
   match '/login' => 'user_sessions#new', :as => :login
   match '/register' => 'users#create', :as => :register
   match '/signup' => 'users#new', :as => :signup
   match '/rating' => 'rating#index', :as => :rating #:register
   match '/register/:activation_code' => 'activations#new', :as => :register
   match '/activate/:id' => 'activations#create', :as => :activate
   
   #Resources
   resource :account, :controller => "users"
   resources :password_resets
   resource :user_session
   resources :users do
     resources :characters
     resources :guilds
     resources :raids
   end
       
   resources :guilds do
     resources :characters
     resources :users
     resources :raids
     resources :newsentries
     resources :events
     resources :statistics
     resources :widgets
   end
   resources :characters do
     resources :events
   end
   resources :events
   resources :newsentries
   
   resources :raids do
     resources :attendances
   end
   resources :attendances
   
   #Guild Join Route
   match '/guilds/:id/join/:token' => 'guilds#join'
   
   #Default Route
   match ':controller/:id/:action(.:format)'
end

app/views/shared/_event.html.erb
<div class="event"><%= link_to event.character.name, :controller => 'characters', :action => 'show', :id => event.character.id if event.character %> <%= t("events.actiontexts.#{event.action}", :content => event.content) %> (<%=h time_ago_in_words(event.created_at) %> ago)</div>

app/views/shared/_newsentry.html.erb
<h3>
	<a><%= newsentry.title %></a>
</h3>
<div>
	<div>
		<%= sanitize newsentry.body  %>
		<div class="news_menu">
			<%= link_to image_tag("icons/page_edit.png", :alt => t('users.edit'), :size => "16x16"), edit_guild_newsentry_path(guild,newsentry) %>
			<%= link_to image_tag("icons/kick.png", :alt => t('users.delete'), :size => "16x16"), newsentry, :confirm => t('confirmation'), :method => :delete %>
		</div>
		<div class="news_footer">
			<div class="news_author"><%= link_to(newsentry.user.login, user_path(newsentry.user)) %></div>
			<div class="news_time"><%=h newsentry.updated_at %></div>
		</div>		
	</div>
</div>

app/views/shared/_tabs.html.erb
<% content_for :tabs do %>
<% if tabs.is_a? Array then %>
<!-- Tabs Div -->
<div id="secnav">
	<ul>
	<% tabs.each do |tab| %>
		<% unless tab.empty? %>
		<%= "<li>#{tab.html_safe}</li>".html_safe %>
		<% else %>
		<%= "<li class=\"spacer\">&nbsp;</li>".html_safe %>
		<% end %>
	<% end %>
	</ul>
</div>
<!-- End Tabs Div -->
<% end %>
<% end %>

app/views/shared/_tooltip.html.erb
<div class='tooltip' style="<%= style %>"><%= text %></div>
<script type="text/javascript">$(document).ready(function(){$("#<%=h id %>").tooltip();});</script>