config/routes.rb
RisingGuilds::Application.routes.draw do 
   root :to =>"pages#show", :id => "home"
   
   # Static Pages Route
   match 'pages/:id' => 'pages#show'
   
   # Authentication Routes
   match '/logout' => 'user_sessions#destroy', :as => :logout
   match '/login' => 'user_sessions#new', :as => :login
   match '/register' => 'users#create', :as => :register
   match '/signup' => 'users#new', :as => :signup
   match '/rating' => 'rating#index', :as => :rating #:register
   match '/register/:activation_code' => 'activations#new', :as => :register
   match '/activate/:id' => 'activations#create', :as => :activate
   
   #Resources
   resource :account, :controller => "users"
   resources :password_resets
   resource :user_session
   resources :users do
     resources :characters
     resources :guilds
     resources :raids
   end
       
   resources :guilds do
     resources :characters
     resources :users
     resources :raids
     resources :newsentries
     resources :events
     resources :statistics
     resources :widgets
   end
   resources :characters do
     resources :events
   end
   resources :events
   resources :newsentries
   
   resources :raids do
     resources :attendances
   end
   resources :attendances
   
   #Guild Join Route
   match '/guilds/:id/join/:token' => 'guilds#join'
   
   #Default Route
   match ':controller/:id/:action(.:format)'
end

app/models/event.rb
class Event < ActiveRecord::Base
  include ActionView::Helpers::DateHelper
  
  belongs_to :character
  belongs_to :guild, :touch => true
  
  cattr_reader :per_page
  @@per_page = 10
  
  scope :visible, where(:visible => true)
  
  def character_name
    unless self.character.blank?
      self.character.name
    else
      nil
    end
  end
  
  def created_ago
    time_ago_in_words(self.created_at)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  filter_resource_access
  
  layout :choose_layout
  
  # GET /events
  # GET /events.xml
  def index
    @events = Event.visible.where(:guild_id => params[:guild_id]) unless params[:guild_id].nil?
    @events = Event.visible.where(:character_id => params[:character_id]) unless params[:character_id].nil?
    @events = @events.order("created_at DESC").paginate(:per_page => 10, :page => params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
      format.js
      format.json { render :json => @events.to_json(:methods => [:character_name, :text, :created_ago], :only => [:action, :content, :name, :created_at, :text, :created_ago]), :callback => params[:callback]}
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit

  end

  # POST /events
  # POST /events.xml
  def create
    respond_to do |format|
      if @event.save
        flash[:notice] = t(:created, :item => 'event')
        format.html { redirect_to(@event) }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update

    respond_to do |format|
      if @event.update_attributes(params[:event])
        flash[:notice] = t(:updated, :item => 'event')
        format.html { redirect_to(@event) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
  
  def choose_layout
    unless params[:guild_id].nil?
      return 'guild_tabs'
    else
      return 'application'
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_events.erb
<div id="events">
	<div class="pagination">
	<%= render :partial => 'shared/event', :collection => @events %>
	<%= will_paginate @events, :class => "pagination ajax" %>
	</div>
</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= form_for(@event) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :action %><br />
    <%= f.text_field :action %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </p>
  <p>
    <%= f.label :guild_id %><br />
    <%= f.text_field :guild_id %>
  </p>
  <p>
    <%= f.label :character_id %><br />
    <%= f.text_field :character_id %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<%= render "events" %>

app/views/events/index.js.erb
$("#events").html("<%= raw(escape_javascript(render :partial => 'events')) %>");

app/views/events/new.html.erb
<h1>New event</h1>

<%= form_for(@event) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :action %><br />
    <%= f.text_field :action %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </p>
  <p>
    <%= f.label :guild_id %><br />
    <%= f.text_field :guild_id %>
  </p>
  <p>
    <%= f.label :character_id %><br />
    <%= f.text_field :character_id %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p>
  <b><%= t('events.labels.action') %>:</b>
  <%=h @event.action %>
</p>

<p>
  <b><%= t('events.labels.content') %>:</b>
  <%=h @event.content %>
</p>

<p>
  <b><%= t('events.labels.guild') %>:</b>
  <%=h @event.guild_id %>
</p>

<p>
  <b><%= t('character') %>:</b>
  <%=h @event.character_id %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>